"""Persistence ports used by application use cases."""

from __future__ import annotations

from typing import Protocol

from ..domain.jobs.job import Job
from ..domain.project import Episode, Project


class ProjectRepository(Protocol):
    def add(self, project: Project) -> None: ...
    def get(self, project_id: str) -> Project | None: ...


class EpisodeRepository(Protocol):
    def add(self, episode: Episode) -> None: ...
    def get_by_source(self, project_id: str, source_sha256: str) -> Episode | None: ...
    def next_ordinal(self, project_id: str) -> int: ...


class JobRepository(Protocol):
    def find_by_input_hash(self, input_hash: str) -> Job | None: ...
    def save(self, job: Job) -> None: ...
    def append_event(self, job_id: str, state: str, message_key: str) -> None: ...
